[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "avatar-wiki"
authors = [{name = "Rui Luo", email = "luo.rui@northeastern.edu"}]
dynamic = ["version", "description"]
